### ISSUE TITLE
Bridge Issue

### ISSUE THREAD

**Issue by Rblaine5734** [paradiso-io/bridge-issues#1]
I do not know where else to go as I have tried all other channels. I’ve attempted to Bridge Ethereum to Casper and the claim is still open after 20 hours. I have not had this issue before and am not receiving any help.

**Comment by khaihkd** [comment]
can you provide us with more info (your wallet address, tx bridge from ethereum)

**Comment by Rblaine5734** [comment]
https://etherscan.io/tx/0x3ff28f61ca86c12a1f4d5100513fa0c6f53ff58ef2a1e33da4289aebbb902950

**Comment by Rblaine5734** [comment]
> can you provide us with more info (your wallet address, tx bridge from ethereum)

https://etherscan.io/tx/0x3ff28f61ca86c12a1f4d5100513fa0c6f53ff58ef2a1e33da4289aebbb902950

**Comment by khaihkd** [comment]
Got it, we will answer asap. Sorry for this inconvenience

**Comment by Rblaine5734** [comment]
> Got it, we will answer asap. Sorry for this inconvenience 

Thank you.  Please advise when issues are resolved.
